configs:
  - id: kafka-consumer-low-throughput
    type:
      settings:
        schema: builtin:davis.anomaly-detectors
        schemaVersion: 1.0.16
        scope: environment
    config:
      template: low-consumer-throughput.json

  - id: kafka-low-replication-efficiency
    type:
      settings:
        schema: builtin:davis.anomaly-detectors
        schemaVersion: 1.0.16
        scope: environment
    config:
      template: low-replication-efficiency.json
